### ISSUE TITLE
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by theCuriousHAT** [hanxiao/bert-as-service#548]
**Prerequisites**

> Please fill in by replacing `[ ]` with `[x]`.

* [x] Are you running the latest `bert-as-service`?
* [x] Did you follow [the installation](https://github.com/hanxiao/bert-as-service#install) and [the usage](https://github.com/hanxiao/bert-as-service#usage) instructions in `README.md`?
* [x] Did you check the [FAQ list in `README.md`](https://github.com/hanxiao/bert-as-service#speech_balloon-faq)?
* [x] Did you perform [a cursory search on existing issues](https://github.com/hanxiao/bert-as-service/issues)?

**System information**

> Some of this information can be collected via [this script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh).

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0 
- Python version: 3.7.4
- `bert-as-service` version: 1.10
- GPU model and memory:
- CPU model and memory:

---

### Description
Bert service is working fine for me in the local.
However, when I am trying to run a docker image, I am facing an issue.

Then this issue shows up:
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory.

What can be done on this?

**Comment by theCuriousHAT** [comment]
Resolved the issue
using tensorflow 1.14.0 wont cause this issue.

**Comment by Azleal** [comment]
> Resolved the issue
> using tensorflow 1.14.0 wont cause this issue.

@theCuriousHAT  hi there, did you just change the version of base image in the Dockerfile to 1.14.0 and it worked? 
I encountered the same problem when using docker. could you please tell me how did you solve this out, thanks~

**Comment by Azleal** [comment]
> > Resolved the issue
> > using tensorflow 1.14.0 wont cause this issue.
> 
> @theCuriousHAT hi there, did you just change the version of base image in the Dockerfile to 1.14.0 and it worked?
> I encountered the same problem when using docker. could you please tell me how did you solve this out, thanks~

to anyone who has encountered the same issue. here is the I solved it using docker.
- 1. `git clone https://github.com/hanxiao/bert-as-service.git`
- 2. change the base image version to `1.15.3-py3`, i.e. `FROM tensorflow/tensorflow:1.15.3-py3`
- 3. after build the image, using `docker run -dit -p 5555:5555 -p 5556:5556 -v $PATH_MODEL:/model -t bert-as-service $NUM_WORKER` as mentioned in readme to start up. NOTICE: I removed `--runtime`, because the machine I'm using doesn't have a GPU.

here's a snapshot of the result after a successful starting up↓

![image](https://user-images.githubusercontent.com/7901126/102564080-abf4d500-4115-11eb-8600-6d92d9216dec.png)
